### ISSUE TITLE
[0.1.8]升级中报错

### ISSUE THREAD

**Issue by wuxianliang** [waditu/tushare#1]
@jimmysoa 

您好

这个项目太有用了，感谢！

我在运行0.1.8升级命令式，报错
```
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import tushare
  File "/Users/Liang/tushare/tushare/__init__.py", line 7, in <module>
    from tushare.stock.fundamental import (get_stock_basics, get_report_data,
  File "/Users/Liang/tushare/tushare/stock/fundamental.py", line 11, in <module>
    import lxml.html
ImportError: No module named lxml.html
```

**Comment by wuxianliang** [comment]
按照StackOverflow上的第一个方法，解决了问题
http://stackoverflow.com/questions/23172384/lxml-runtime-error-reason-incompatible-library-version-etree-so-requires-vers

**Comment by wuxianliang** [comment]
在成功升级之后，在ipython里，
```
import tushare

print tushare.__version__

```
看到的还是0.1.7。没改版本号吧？:-)

**Comment by jimmysoa** [comment]
暂时不用升级也没问题，0.1.8只是在import导入方式做了修改，有问题请及时通过QQ或Email联系我
