### ISSUE TITLE
UnicodeEncodeError when output csv files

### ISSUE THREAD

**Issue by slippedgrey** [waditu/tushare#115]
我想把 request 到的每分钟的realtime_quote 数据写到一个csv 文件里，用网站上提供的方法：
`import tushare as ts
import os

filename = 'c:/day/bigfile.csv'
for code in ['000875', '600848', '000981']:
    df = ts.get_hist_data(code)
    if os.path.exists(filename):
        df.to_csv(filename, mode='a', header=None)
    else:
        df.to_csv(filename)

raise了一个 exception：
traceback 显示如下 我用的是 anaconda 安装的是 python 2.7.11
请问这个有解嘛
谢谢了！

Traceback (most recent call last):

  File "<ipython-input-23-80d4058aa1c9>", line 1, in <module>
    runfile('C:/Users/thean_000/.spyder2/temp.py', wdir='C:/Users/thean_000/.spyder2')

  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/thean_000/.spyder2/temp.py", line 16, in <module>
    df.to_csv(filename)

  File "C:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 1343, in to_csv
    formatter.save()

  File "C:\Anaconda2\lib\site-packages\pandas\core\format.py", line 1550, in save
    self._save()

  File "C:\Anaconda2\lib\site-packages\pandas\core\format.py", line 1651, in _save
    self._save_chunk(start_i, end_i)

  File "C:\Anaconda2\lib\site-packages\pandas\core\format.py", line 1677, in _save_chunk
    lib.write_csv_rows(self.data, ix, self.nlevels, self.cols, self.writer)

  File "pandas\lib.pyx", line 1078, in pandas.lib.write_csv_rows (pandas\lib.c:19848)

UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

**Comment by jimmysoa** [comment]
在代码前面添加编码设置，具体你可以baidu一下。

**Comment by slippedgrey** [comment]
谢谢你的回复 您知道怎么 将多次 request到的数据存入一个 excel里面吗？
就像您给的csv的例子？

**Comment by jimmysoa** [comment]
使用append参数

**Comment by slippedgrey** [comment]
多谢回复 之前没想到dataframe格式也可以 append, 问题已经解决了 thank you sharing!

**Comment by jimmysoa** [comment]
@slippedgrey 不客气

**Comment by slippedgrey** [comment]
hello, thank you for your reply
I have solved the problem(at least it works) using following code
hope it can be useful for other users!

`import` tushare as ts
import pandas as pd
import time
list_of_dfs=[]
for i in range(5):
    list_of_dfs.append(ts.get_realtime_quotes('000875'))
    time.sleep(1)
full_df=pd.concat(list_of_dfs)
full_df.to_excel(r'C:\Users\000875.xlsx)``

**Comment by slippedgrey** [comment]
如何解决 unicodeEncodeErr：

import sys  

reload(sys)  
sys.setdefaultencoding('utf8')
