### ISSUE TITLE
与 pandas 0.25.1 不兼容

### ISSUE THREAD

**Issue by johnwangwjq** [waditu/tushare#1169]
把 pandas 版本从 `0.23.3`  升级到 `0.25.1` 后，使用tushare sdk时出现以下异常：
```python
Traceback (most recent call last):
  ...
  File "C:\Programs\anaconda3\envs\p3t\lib\site-packages\tushare\__init__.py", line 11, in <module>
    from tushare.stock.trading import (get_hist_data, get_tick_data,
  File "C:\Programs\anaconda3\envs\p3t\lib\site-packages\tushare\stock\trading.py", line 20, in <module>
    from pandas.compat import StringIO
ImportError: cannot import name 'StringIO'
```

请问有何建议？ 必须把 pandas 回退到老版本吗？

BTW, tushare 版本是 `1.2.35`。

**Comment by jimmysoa** [comment]
Tushare 请升级到最新版，谢谢
