### ISSUE TITLE
tusahre安装问题：Library not loaded：libxml2.2dylb

### ISSUE THREAD

**Issue by Terry93** [waditu/tushare#118]
如题，下面是我的错误：

mac 10.11.4，conda安装完libxslt、libslt以及pip安装完lxml

```
    Using cached tushare-0.5.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7h/frvrv8td7tl3qk6mld7z3_l80000gn/T/pip-build-CVR9h3/tushare/setup.py", line 4, in <module>
        import tushare
      File "/private/var/folders/7h/frvrv8td7tl3qk6mld7z3_l80000gn/T/pip-build-CVR9h3/tushare/tushare/__init__.py", line 7, in <module>
        from tushare.stock.trading import (get_hist_data, get_tick_data,
      File "/private/var/folders/7h/frvrv8td7tl3qk6mld7z3_l80000gn/T/pip-build-CVR9h3/tushare/tushare/stock/trading.py", line 13, in <module>
        import lxml.html
      File "/Users/Terry_Yang/miniconda2/lib/python2.7/site-packages/lxml/html/__init__.py", line 54, in <module>
        from .. import etree
    ImportError: dlopen(/Users/Terry_Yang/miniconda2/lib/python2.7/site-packages/lxml/etree.so, 2): Library not loaded: libxml2.2.dylib
      Referenced from: /Users/Terry_Yang/miniconda2/lib/python2.7/site-packages/lxml/etree.so
      Reason: Incompatible library version: etree.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
```

**Comment by jimmysoa** [comment]
安装一个mac版的Anaconda，可避免出现类似问题。
