### ISSUE TITLE
ImportError: cannot import name 'StringIO' from 'pandas.compat'

### ISSUE THREAD

**Issue by newmann** [waditu/tushare#1277]
python : 3.7.1
pandas : 1.0.0
tushare: 1.2.48

import tushare 报错：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\dev\Anaconda3\envs\tushare\lib\site-packages\tushare\__init__.py", line 11, in <module>
    from tushare.stock.trading import (get_hist_data, get_tick_data,
  File "c:\dev\Anaconda3\envs\tushare\lib\site-packages\tushare\stock\trading.py", line 24, in <module>
    from tushare.stock.fundamental import get_stock_basics
  File "c:\dev\Anaconda3\envs\tushare\lib\site-packages\tushare\stock\fundamental.py", line 19, in <module>
    from pandas.compat import StringIO
ImportError: cannot import name 'StringIO' from 'pandas.compat' (c:\dev\Anaconda3\envs\tushare\lib\site-packages\pandas\compat\__init__.py)

**Comment by wwdlook** [comment]
I have the same problem, and my python version is py3.6

**Comment by iseelearn** [comment]
me too！

**Comment by jerrychong25** [comment]
Same issues here. 

@newmann @wwdlook @libsyc Do you all already have solution on this issue?

**Comment by jerrychong25** [comment]
Fixed this issue by upgrading to latest tushare latest version, with following commands:
`pip install tushare --upgrade`
