### ISSUE TITLE
升级pandas到1.0.0出现的错误

### ISSUE THREAD

**Issue by mpkzo** [waditu/tushare#1278]
ID： 236559
升级pandas到1.0.0出现的
Traceback (most recent call last):
  File "D:\StockAnalize\tradeW.pyw", line 15, in <module>
    import tushare as ts
  File "D:\Python\lib\site-packages\tushare\__init__.py", line 11, in <module>
    from tushare.stock.trading import (get_hist_data, get_tick_data,
  File "D:\Python\lib\site-packages\tushare\stock\trading.py", line 24, in <module>
    from tushare.stock.fundamental import get_stock_basics
  File "D:\Python\lib\site-packages\tushare\stock\fundamental.py", line 19, in <module>
    from pandas.compat import StringIO
ImportError: cannot import name 'StringIO' from 'pandas.compat' (D:\Python\lib\site-packages\pandas\compat\__init__.py)

**Comment by DamienGong** [comment]
Have the same issue as well when import tushare as ts
It was under Linux and I cloned the project then installed it by 'python3 setup.py install'
Pending on a fix. Thanks

**Comment by jerrychong25** [comment]
Fixed this issue by upgrading to latest tushare latest version, with following commands:
`pip install tushare --upgrade`
