### ISSUE TITLE
用pro_bar调用分钟数据线数据报错

### ISSUE THREAD

**Issue by bizeasy17** [waditu/tushare#1282]
e.g. df = ts.pro_bar( ts_code='000001.SZ', freq='60', adj='qfq', start_date='20181001', end_date='20181011')
报错信息如下
local variable 'data' referenced before assignment
local variable 'data' referenced before assignment
local variable 'data' referenced before assignment
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tushare/pro/data_pro.py", line 189, in pro_bar
    raise IOError('ERROR.')
OSError: ERROR.

**Comment by jimmysoa** [comment]
freq='60min'

另外，请保持tushare最新版
