### ISSUE TITLE
get_realtime_quotes接口部分股票报错

### ISSUE THREAD

**Issue by skxman** [waditu/tushare#1289]
600004股票返回的是34个列，tushare处理默认33列，导致报错，如下报错信息。
ID:  285759

>>> ts.get_realtime_quotes('600004')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/song/Devtool/anaconda3/lib/python3.6/site-packages/tushare/stock/trading.py", line 385, in get_realtime_quotes
    df = pd.DataFrame(data_list, columns=ct.LIVE_DATA_COLS)
  File "/Users/song/Devtool/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 435, in __init__
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "/Users/song/Devtool/anaconda3/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 404, in to_arrays
    dtype=dtype)
  File "/Users/song/Devtool/anaconda3/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 436, in _list_to_arrays
    coerce_float=coerce_float)
  File "/Users/song/Devtool/anaconda3/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 492, in _convert_object_array
    con=len(content)))
AssertionError: 33 columns passed, passed data had 34 columns

**Comment by jimmysoa** [comment]
Tushare 升级到最新版，这个问题很早就修复了
