### ISSUE TITLE
get_tick_data返回None

### ISSUE THREAD

**Issue by zhjsoftware** [waditu/tushare#1333]
在使用tushare.get_tick_data时返回None，日期'2020-04-08', 但是日期改成'2020-04-07'或其他日期时，可以返回数据，是否有接口改动？

**Comment by huangyisan** [comment]
我也发现这个情况。最近股票接口是否有大面积整顿？因为我实时交易用的stock.gtimg.cn的接口昨天反馈无法更新最新实时数据，访问永远都是老数据。
样例：http://stock.gtimg.cn/data/index.php?appn=detail&action=data&c=sh600000&p=40

**Comment by easyQuant** [comment]
是新浪和腾讯的接口下线了 现在只能使用 get_tick_data(code=None, date=None, src="sn")

**Comment by easyQuant** [comment]
> 我也发现这个情况。最近股票接口是否有大面积整顿？因为我实时交易用的stock.gtimg.cn的接口昨天反馈无法更新最新实时数据，访问永远都是老数据。
> 样例：http://stock.gtimg.cn/data/index.php?appn=detail&action=data&c=sh600000&p=40

我看了下源码 貌似是新浪和腾讯的接口下线了 现在只能使用 get_tick_data(code=None, date=None, src="nt")

**Comment by zhjsoftware** [comment]
> > 我也发现这个情况。最近股票接口是否有大面积整顿？因为我实时交易用的stock.gtimg.cn的接口昨天反馈无法更新最新实时数据，访问永远都是老数据。
> > 样例：http://stock.gtimg.cn/data/index.php?appn=detail&action=data&c=sh600000&p=40
> 
> 我看了下源码 貌似是新浪和腾讯的接口下线了 现在只能使用 get_tick_data(code=None, date=None, src="nt")

对的，老早之前新浪就停更数据了，换成了腾讯，结果现在也停更了，现在在用nt的数据，但是格式有点不一样，当然我可以本地处理下，我最担心的是哪天nt也停更了怎么办，各位大佬有稳定的数据源吗？付费的也可以考虑。

**Comment by wintonzheng** [comment]
同求稳定数据来源付费也行。。。

**Comment by huangyisan** [comment]
> > > 我也发现这个情况。最近股票接口是否有大面积整顿？因为我实时交易用的stock.gtimg.cn的接口昨天反馈无法更新最新实时数据，访问永远都是老数据。
> > > 样例：http://stock.gtimg.cn/data/index.php?appn=detail&action=data&c=sh600000&p=40
> > 
> > 
> > 我看了下源码 貌似是新浪和腾讯的接口下线了 现在只能使用 get_tick_data(code=None, date=None, src="nt")
> 
> 对的，老早之前新浪就停更数据了，换成了腾讯，结果现在也停更了，现在在用nt的数据，但是格式有点不一样，当然我可以本地处理下，我最担心的是哪天nt也停更了怎么办，各位大佬有稳定的数据源吗？付费的也可以考虑。

nt的可以使用么？ 我这边使用直接异常。
>>> code='sh600000'
>>> date = '2019-11-25'
>>> ts.get_tick_data(code, date=date, src='nt')
HTTP Error 404: Not Found
HTTP Error 404: Not Found
HTTP Error 404: Not Found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hysan\AppData\Local\Programs\Python\Python36\lib\site-packages\tushare\stock\trading.py", line 190, in get_tick_data
    raise IOError(ct.NETWORK_URL_ERROR_MSG)
OSError: 获取失败，请检查网络.

**Comment by huangyisan** [comment]
> > > > 我也发现这个情况。最近股票接口是否有大面积整顿？因为我实时交易用的stock.gtimg.cn的接口昨天反馈无法更新最新实时数据，访问永远都是老数据。
> > > > 样例：http://stock.gtimg.cn/data/index.php?appn=detail&action=data&c=sh600000&p=40
> > > 
> > > 
> > > 我看了下源码 貌似是新浪和腾讯的接口下线了 现在只能使用 get_tick_data(code=None, date=None, src="nt")
> > 
> > 
> > 对的，老早之前新浪就停更数据了，换成了腾讯，结果现在也停更了，现在在用nt的数据，但是格式有点不一样，当然我可以本地处理下，我最担心的是哪天nt也停更了怎么办，各位大佬有稳定的数据源吗？付费的也可以考虑。
> 
> nt的可以使用么？ 我这边使用直接异常。
> 
> > > > code='sh600000'
> > > > date = '2019-11-25'
> > > > ts.get_tick_data(code, date=date, src='nt')
> > > > HTTP Error 404: Not Found
> > > > HTTP Error 404: Not Found
> > > > HTTP Error 404: Not Found
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "C:\Users\hysan\AppData\Local\Programs\Python\Python36\lib\site-packages\tushare\stock\trading.py", line 190, in get_tick_data
> > > > raise IOError(ct.NETWORK_URL_ERROR_MSG)
> > > > OSError: 获取失败，请检查网络.

已经解决问题。
网易传入code不需要添加sh或者sz前缀。其0表示sh, 1表示sz。

**Comment by amylaogong** [comment]
> 我也发现这个情况。最近股票接口是否有大面积整顿？因为我实时交易用的stock.gtimg.cn的接口昨天反馈无法更新最新实时数据，访问永远都是老数据。
> 样例：http://stock.gtimg.cn/data/index.php?appn=detail&action=data&c=sh600000&p=40
> 
> 我看了下源码 貌似是新浪和腾讯的接口下线了 现在只能使用 get_tick_data(code=None, date=None, src="nt")
20200429测试，nt也无法访问了，改成tt倒还可以的
为了保险，还是趁着能访问的时候赶紧把数据扒拉下来，存在本地或者存在自己服务器上吧，再以后就每天扒拉一下当天的分笔数据保存

**Comment by easyQuant** [comment]
> > 我也发现这个情况。最近股票接口是否有大面积整顿？因为我实时交易用的stock.gtimg.cn的接口昨天反馈无法更新最新实时数据，访问永远都是老数据。
> > 样例：http://stock.gtimg.cn/data/index.php?appn=detail&action=data&c=sh600000&p=40
> > 我看了下源码 貌似是新浪和腾讯的接口下线了 现在只能使用 get_tick_data(code=None, date=None, src="nt")
> > 20200429测试，nt也无法访问了，改成tt倒还可以的
> > 为了保险，还是趁着能访问的时候赶紧把数据扒拉下来，存在本地或者存在自己服务器上吧，再以后就每天扒拉一下当天的分笔数据保存

貌似当日的需要18:00之后才能获取吧

**Comment by huangyisan** [comment]
tt接口前几天恢复正常了。nt的没有尝试，前几天存在重复数据的问题。
