### ISSUE TITLE
获取个股信息地雷数据get_notices() 报错

### ISSUE THREAD

**Issue by qq12326023** [waditu/tushare#154]
>>> import tushare as ts
>>> ts.get_notices('603936','2016-06-16')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\tushare\stock\newsevent.py", line 123, in get_notices
    title = td.xpath('th/a/text()')[0]
IndexError: list index out of range

**Comment by jimmysoa** [comment]
看了下好像是没有这天的数据，你先不加日期的参数看看。
