### ISSUE TITLE
get_today_ticks 提示网络出错

### ISSUE THREAD

**Issue by muyangquan** [waditu/tushare#162]
'detailPages'
'detailPages'
'detailPages'
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    df = ts.get_today_ticks('300395')
  File "/opt/test/python/tushare/env/lib/python2.7/site-packages/tushare/stock/trading.py", line 254, in get_today_ticks
    raise IOError(ct.NETWORK_URL_ERROR_MSG)
IOError: 获取失败，请检查网络和URL

**Comment by muyangquan** [comment]
获取别的接口是可以的，这就能断定是该接口出问题！
