### ISSUE TITLE
import tushare时报错

### ISSUE THREAD

**Issue by wuyunjiejie** [waditu/tushare#1628]
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import tushare as ts
  File "C:\Program Files\Python37\lib\site-packages\tushare\__init__.py", line 82, in <module>
    from tushare.pro.data_pro import (pro_api, pro_bar, subs, ht_subs)
  File "C:\Program Files\Python37\lib\site-packages\tushare\pro\data_pro.py", line 14, in <module>
    from tushare.subs.ts_subs import Subs
  File "C:\Program Files\Python37\lib\site-packages\tushare\subs\ts_subs.py", line 20, in <module>
    from websocket import WebSocketConnectionClosedException
ImportError: cannot import name 'WebSocketConnectionClosedException' from 'websocket' (C:\Users\wuyunjie\AppData\Roaming\Python\Python37\site-packages\websocket\__init__.py)

尝试过在cmd中pip install websocket以及pip install --upgrade websocket均无果。请问应该如何解决？谢谢

**Comment by wuyunjiejie** [comment]
我在jupyter notebook环境下使用的tushare
