### ISSUE TITLE
installer 打包时候会提示错误

### ISSUE THREAD

**Issue by jianyuanyang** [waditu/tushare#1645]
1.2.62可以打包成功,但是在请求数据的时候会报403错误
1.2.84打包的时候报错
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 2556: invalid continuation byte

**Comment by jianyuanyang** [comment]
具体错误如下:
18475 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'd:\\python\\python37\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
Traceback (most recent call last):
  File "d:\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python\Python37\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "d:\python\python37\lib\site-packages\PyInstaller\__main__.py", line 126, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "d:\python\python37\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "d:\python\python37\lib\site-packages\PyInstaller\building\build_main.py", line 815, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "d:\python\python37\lib\site-packages\PyInstaller\building\build_main.py", line 762, in build
    exec(code, spec_namespace)
  File "E:\python\DingPan\dp.spec", line 19, in <module>
    noarchive=False)
  File "d:\python\python37\lib\site-packages\PyInstaller\building\build_main.py", line 294, in __init__
    self.__postinit__()
  File "d:\python\python37\lib\site-packages\PyInstaller\building\datastruct.py", line 159, in __postinit__
    self.assemble()
  File "d:\python\python37\lib\site-packages\PyInstaller\building\build_main.py", line 467, in assemble
    priority_scripts.append(self.graph.add_script(script))
  File "d:\python\python37\lib\site-packages\PyInstaller\depend\analysis.py", line 305, in add_script
    pathname)
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1433, in add_script
    self._process_imports(n)
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2303, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1506, in import_hook
    source_package, target_module_partname, level)
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1685, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "d:\python\python37\lib\site-packages\PyInstaller\depend\analysis.py", line 448, in _safe_import_module
    module_basename, module_name, parent_package)
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2303, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1518, in import_hook
    submodule = self._safe_import_module(head, mname, submodule)
  File "d:\python\python37\lib\site-packages\PyInstaller\depend\analysis.py", line 448, in _safe_import_module
    module_basename, module_name, parent_package)
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2303, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1518, in import_hook
    submodule = self._safe_import_module(head, mname, submodule)
  File "d:\python\python37\lib\site-packages\PyInstaller\depend\analysis.py", line 448, in _safe_import_module
    module_basename, module_name, parent_package)
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2303, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1518, in import_hook
    submodule = self._safe_import_module(head, mname, submodule)
  File "d:\python\python37\lib\site-packages\PyInstaller\depend\analysis.py", line 448, in _safe_import_module
    module_basename, module_name, parent_package)
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2303, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1518, in import_hook
    submodule = self._safe_import_module(head, mname, submodule)
  File "d:\python\python37\lib\site-packages\PyInstaller\depend\analysis.py", line 448, in _safe_import_module
    module_basename, module_name, parent_package)
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2053, in _safe_import_module
    (module, co) = self._load_module(module_name, pathname, loader)
  File "d:\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2143, in _load_module
    src = loader.get_source(partname)
  File "<frozen importlib._bootstrap_external>", line 783, in get_source
  File "<frozen importlib._bootstrap_external>", line 566, in decode_source

**Comment by jimmysoa** [comment]
tushare升级到最新版

**Comment by jianyuanyang** [comment]
tushare的最新版就是1.2.84吧?

**Comment by jianyuanyang** [comment]
好了,最新版本 ,1.2.85
