### ISSUE TITLE
pro.daily()中ts_code参数好像会因为长度太长而执行失败

### ISSUE THREAD

**Issue by beatttt** [waditu/tushare#1670]
daily_df = self.pro.daily(ts_code=self.ts_code, trade_date=start_date)

报错如下：
Traceback (most recent call last):
  File "/home/scholar/documents/WorkFile/c++_projects/tushare/utils.py", line 76, in <module>
    print(data.get_stock_by_name("大港股份", "20220810"))
  File "/home/scholar/documents/WorkFile/c++_projects/tushare/utils.py", line 42, in get_stock_by_name
    daily_df = self.pro.daily(ts_code=self.ts_code, trade_date=date)
  File "/home/scholar/miniconda3/lib/python3.9/site-packages/tushare/pro/client.py", line 44, in query
    raise Exception(result['msg'])
Exception: 服务器错误，请稍后再试！期待您能把错误反馈给我们，谢谢！

**Comment by Tanglumy** [comment]
我也遇到了一样的问题，请问有啥解决思路
