### ISSUE TITLE
Ubuntu 安装 TuShare 失败

### ISSUE THREAD

**Issue by newebug** [waditu/tushare#211]
Collecting tushare
  Downloading tushare-0.5.1.zip (100kB)
    100% |████████████████████████████████| 102kB 5.0kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2ByvTF/tushare/setup.py", line 4, in <module>
        import tushare
      File "/tmp/pip-build-2ByvTF/tushare/tushare/**init**.py", line 7, in <module>
        from tushare.stock.trading import (get_hist_data, get_tick_data,
      File "/tmp/pip-build-2ByvTF/tushare/tushare/stock/trading.py", line 13, in <module>
        import lxml.html
    ImportError: No module named lxml.html

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2ByvTF/tushare/

**Comment by jimmysoa** [comment]
先装一下lxml试试看看

**Comment by newebug** [comment]
确实是没有 lxml，后来提示 没有安装 pandas，现在搞好了，感谢！很不错的软件
