### ISSUE TITLE
get_stock_basics() timeout问题

### ISSUE THREAD

**Issue by panins** [waditu/tushare#219]
`>>> a=ts.get_stock_basics()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tushare/stock/fundamental.py", line 44, in get_stock_basics
    text = urlopen(request, timeout=10).read()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 461, in read
    s = self._safe_read(self.length)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 607, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out`

通过本机和阿里云都出现超时，一个小时之前都是正常的，是服务器问题么。

**Comment by panins** [comment]
现在恢复正常了。

**Comment by Mount565** [comment]
这个调用时不时地出问题，不知道怎么回事？
