### ISSUE TITLE
AttributeError: module 'tushare' has no attribute '__version__'

### ISSUE THREAD

**Issue by ring0li** [waditu/tushare#241]
pip3 install tushare 提示安装成功
控制台输出：
```shell
/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/bin/python3.5 /Users/liuli/github/study/tushare.py
Traceback (most recent call last):
  File "/Users/liuli/github/study/tushare.py", line 4, in <module>
    import tushare
  File "/Users/liuli/github/study/tushare.py", line 6, in <module>
    print(tushare.__version__)
AttributeError: module 'tushare' has no attribute '__version__'

Process finished with exit code 1
```
哪里错了呢？

**Comment by jimmysoa** [comment]
不要以tushare作为文件名

**Comment by ring0li** [comment]
谢谢你
