### ISSUE TITLE
试了下新的top10_holder网络连接错误

### ISSUE THREAD

**Issue by Bruce-li-92** [waditu/tushare#249]
ts.top10_holders(code="300339")
'ljcy'
'ljcy'
'ljcy'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tushare/stock/reference.py", line 742, in top10_holders
    raise IOError(ct.NETWORK_URL_ERROR_MSG)
OSError: 获取失败，请检查网络和URL

这个是不是网络不稳定造成的？看之前也有类似的issue。

**Comment by xiaomingdaily** [comment]
同问哈，top10_holder怎么使用，在文档里没有看到使用说明

**Comment by qq12326023** [comment]
问题相同： 
  tt=ts.top10_holders(code='603928',year='2017',quarter='2')
  File "C:\Anaconda3\lib\site-packages\tushare\stock\reference.py", line 743, in top10_holders
    raise IOError(ct.NETWORK_URL_ERROR_MSG)
OSError: 获取失败，请检查网络和URL

**Comment by qq12326023** [comment]
但是部分股票又是可以，很奇怪。。。

**Comment by tombluemoon** [comment]
你选择的这个(code='603928',year='2017',quarter='2')的第二季度数据还没有，数据源返回的值部分格式有问题导致的。
