### ISSUE TITLE
股票账号登陆的时候报错

### ISSUE THREAD

**Issue by yishuiliunian** [waditu/tushare#262]
Traceback (most recent call last):
  File "/Users/stonedong/PycharmProjects/ShareTrader/Trader.py", line 9, in <module>
    csc.login()
  File "/Library/Python/2.7/site-packages/tushare/trader/trader.py", line 50, in login
    if self._login(utils.get_vcode('csc', res)) is False:
  File "/Library/Python/2.7/site-packages/tushare/trader/utils.py", line 35, in get_vcode
    vcode = pt.image_to_string(img)
  File "/Library/Python/2.7/site-packages/pytesseract/pytesseract.py", line 161, in image_to_string
    config=config)
  File "/Library/Python/2.7/site-packages/pytesseract/pytesseract.py", line 94, in run_tesseract
    stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by pseudocodes** [comment]
需要把你的`资金账号` 和 `密码` 写在一个 csv 文件里，具体看源码

**Comment by Rockyzsu** [comment]
@yishuiliunian 请问你用的是哪个券商？

**Comment by wqqgt** [comment]
我也遇到了相同的问题，用的是zxjt, 应该是验证码没有识别，识别失败了

**Comment by rickfu415** [comment]
我也遇到了这样的问题，有高手解决了吗？求指导啊

**Comment by fffweb** [comment]
请教下，这个软件能获取50ETF期权的信息吗？
按说明操作，有下面问题
＃获取期权合约编码，交易代码，交易市场，标的等相关信息
**>>> fd = ts.Options()**
璇疯缃€氳仈鏁版嵁鎺ュ彛鐨則oken鍑瘉鐮
**>>> df = fd.Opt(contractStatus='L,DE', field='optID,secShortName,varShortName,listDate')**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python27\lib\site-packages\tushare\datayes\options.py", line 30, in Opt
    varSecID, varticker, field))
  File "D:\Python27\lib\site-packages\tushare\util\common.py", line 84, in getData
    raise e
TypeError: cannot concatenate 'str' and 'NoneType' objects
