### ISSUE TITLE
ts.get_stock_basics() 这个调用的得到的dataframe 没有code 

### ISSUE THREAD

**Issue by Mount565** [waditu/tushare#292]
stock_b = ts.get_stock_basics()
print(stock_b['code'])

运行：
Traceback (most recent call last):
  File "C:\Users\110341\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pandas\indexes\base.py", line 2134, in get_loc
    return self._engine.get_loc(key)
  File "pandas\index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas\index.c:4433)
  File "pandas\index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas\index.c:4279)
  File "pandas\src\hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:13742)
  File "pandas\src\hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:13696)
KeyError: 'code'

如果print(stock_b) ,可以看到code字段，但该字段格式上低于其它字段，貌似作为值显示了。

**Comment by Mount565** [comment]
我的解决方案，写入csv,然后再读取，就有了

**Comment by jimmysoa** [comment]
code是index

**Comment by Mount565** [comment]
@jimmysoa code 不是股票代码吗？如果获得一个股票基本信息表和一个现金流量表，他们以股票代码merge 怎么做呢？
p1 = ts.get_stock_basics()
p2 = ts.ts.get_cashflow_data(2016, 3)
p4=p1.merge(p2,on='code', how='left')

这样会报KeyError: 'code'

将p1和p2本别写入csv文件, 然后再从csv读取，两个新的dataframe, 再以code来merge就没错误了。

why ???

**Comment by jimmysoa** [comment]
把p2的code设置成index，left_index=True,right_index=True

**Comment by Mount565** [comment]
为啥p1的code是index ， p2 的不是？

**Comment by Mount565** [comment]
p1 = p1.reset_index(); 重置p1的index再merge就可以了
