### ISSUE TITLE
[2.0] 升级到2.0之后，运行时报错

### ISSUE THREAD

**Issue by wuxianliang** [waditu/tushare#3]
@jimmysoa
你好

在升级到2.0之后，报错如下，不知如何解决。
```
NiTu:Liang ~$ python dddd.py
Traceback (most recent call last):
  File "dddd.py", line 1, in <module>
    import tushare as ts
  File "/Users/Liang/anaconda/lib/python2.7/site-packages/tushare/__init__.py", line 5, in <module>
    from tushare.stock.trading import (get_hist_data, get_tick_data,
  File "/Users/Liang/anaconda/lib/python2.7/site-packages/tushare/stock/trading.py", line 16, in <module>
    import pandas as pd
  File "/Users/Liang/anaconda/lib/python2.7/site-packages/pandas/__init__.py", line 41, in <module>
    from pandas.core.api import *
  File "/Users/Liang/anaconda/lib/python2.7/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.groupby import Grouper
  File "/Users/Liang/anaconda/lib/python2.7/site-packages/pandas/core/groupby.py", line 15, in <module>
    from pandas.core.frame import DataFrame
  File "/Users/Liang/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 40, in <module>
    from pandas.computation.eval import eval as _eval
  File "/Users/Liang/anaconda/lib/python2.7/site-packages/pandas/computation/eval.py", line 8, in <module>
    from pandas.computation.expr import Expr, _parsers, tokenize_string
  File "/Users/Liang/anaconda/lib/python2.7/site-packages/pandas/computation/expr.py", line 148, in <module>
    (getattr(ast, node) for node in dir(ast))))
  File "/Users/Liang/anaconda/lib/python2.7/site-packages/pandas/computation/expr.py", line 147, in <lambda>
    issubclass(x, ast.AST),
AttributeError: 'module' object has no attribute 'AST'
```

谢谢

**Comment by Zhehao** [comment]
感觉你错误的问题出在import expr的过程，这里有一个链接[http://lovesoo.org/python-script-error-attributeerror-module-object-has-no-attribute-solve-method.html]给你参考下，希望能解决你的问题。

**Comment by jimmysoa** [comment]
看了一下错误日志，问题出在import pandas as pd这个地方，可能是当前console下没法使用pandas包。

**Comment by wuxianliang** [comment]
@Zhehao @jimmysoa 
非常感谢，删掉expr.pyc，这个方法确实管用。但是遗留的问题是，每次使用pandas之前都要事先删一次expr.pyc，而且，就地运行import pandas。如果先回到家目录再运行import pandas，还是同样的错误。
能否根治？

**Comment by jimmysoa** [comment]
建议你搞一个IDE环境统一维护代码，不要在python的console下运行。

**Comment by wuxianliang** [comment]
问题彻底查明了。前些天，我装了bayesdb在家目录下，散落了一些.py文件，我将这些文件清理之后。一切正常。
抱歉，浪费了大家的时间。
