### ISSUE TITLE
Can't run ts.get_stock_basics()

### ISSUE THREAD

**Issue by wengminhua** [waditu/tushare#319]
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (
Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tushare as ts
>>> ts.get_stock_basics()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\tushare\stock\fundamental.py", line 54, in
 get_stock_basics
    text = urlopen(request, timeout=10).read()
  File "C:\Python27\lib\socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "C:\Python27\lib\httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "C:\Python27\lib\socket.py", line 384, in read
    data = self._sock.recv(left)
socket.timeout: timed out

**Comment by dindom999** [comment]
这个接口最近是经常不正常

**Comment by jimmysoa** [comment]
请将tushare升级到最新版即可。

**Comment by yangguang760** [comment]
已升级，仍然timeout
@jimmysoa 

```
/home/yang/E/pyProj/monitor/prog/qstkIntegrate.py in updateOfflineDataFromTSMulti(self, oldFile, newFile, start, threadsCount)
    293         geventList=[]
    294         geventPool = Pool(threadsCount)
--> 295         stkInfo = ts.get_stock_basics()
    296         # stkInfo = ts.get_stock_basics()
    297         tempStkList = set(stkInfo.index.values)

/home/yang/.pyenv/versions/anaconda3-2.4.1/lib/python3.5/site-packages/tushare/stock/fundamental.py in get_stock_basics(date)
     52     datepre = '' if date is None else wdate[0:4] + wdate[4:6] + '/'
     53     request = Request(ct.ALL_STOCK_BASICS_FILE%(datepre, '' if date is None else wdate))
---> 54     text = urlopen(request, timeout=10).read()
     55     text = text.decode('GBK')
     56     text = text.replace('--', '')

/home/yang/.pyenv/versions/anaconda3-2.4.1/lib/python3.5/http/client.py in read(self, amt)
    459             else:
    460                 try:
--> 461                     s = self._safe_read(self.length)
    462                 except IncompleteRead:
    463                     self._close_conn()

/home/yang/.pyenv/versions/anaconda3-2.4.1/lib/python3.5/http/client.py in _safe_read(self, amt)
    605         s = []
    606         while amt > 0:
--> 607             chunk = self.fp.read(min(amt, MAXAMOUNT))
    608             if not chunk:
    609                 raise IncompleteRead(b''.join(s), amt)

/home/yang/.pyenv/versions/anaconda3-2.4.1/lib/python3.5/socket.py in readinto(self, b)
    573         while True:
    574             try:
--> 575                 return self._sock.recv_into(b)
    576             except timeout:
    577                 self._timeout_occurred = True

/home/yang/.pyenv/versions/anaconda3-2.4.1/lib/python3.5/site-packages/gevent/_socket3.py in recv_into(self, *args)
    383                 if ex.args[0] != EWOULDBLOCK or self.timeout == 0.0:
    384                     raise
--> 385             self._wait(self._read_event)
    386 
    387     def send(self, data, flags=0, timeout=timeout_default):

/home/yang/.pyenv/versions/anaconda3-2.4.1/lib/python3.5/site-packages/gevent/_socket3.py in _wait(self, watcher, timeout_exc)
    155             timeout = None
    156         try:
--> 157             self.hub.wait(watcher)
    158         finally:
    159             if timeout is not None:

/home/yang/.pyenv/versions/anaconda3-2.4.1/lib/python3.5/site-packages/gevent/hub.py in wait(self, watcher)
    649         watcher.start(waiter.switch, unique)
    650         try:
--> 651             result = waiter.get()
    652             if result is not unique:
    653                 raise InvalidSwitchError('Invalid switch into %s: %r (expected %r)' % (getcurrent(), result, unique))

/home/yang/.pyenv/versions/anaconda3-2.4.1/lib/python3.5/site-packages/gevent/hub.py in get(self)
    897             self.greenlet = getcurrent()
    898             try:
--> 899                 return self.hub.switch()
    900             finally:
    901                 self.greenlet = None

/home/yang/.pyenv/versions/anaconda3-2.4.1/lib/python3.5/site-packages/gevent/hub.py in switch(self)
    628         if switch_out is not None:
    629             switch_out()
--> 630         return RawGreenlet.switch(self)
    631 
    632     def switch_out(self):

```
