### ISSUE TITLE
get_today_ticks错误：No tables found matching pattern '.+'

### ISSUE THREAD

**Issue by mdsb100** [waditu/tushare#324]
'000006'一会可以，一会不可以

'000002'就不行
感觉和沪深没关系
'600343'
```
[Getting data:]#####################################################################No tables found matching pattern '.+'
No tables found matching pattern '.+'
No tables found matching pattern '.+'
获取失败，请检查网络和URL
[Getting data:]#####################################################################No tables found matching pattern '.+'
No tables found matching pattern '.+'
No tables found matching pattern '.+'
获取失败，请检查网络和URL
[Getting data:]#####################################################################No tables found matching pattern '.+'
No tables found matching pattern '.+'
No tables found matching pattern '.+'
```

**Comment by gzcf** [comment]
除了会出现`No tables found matching pattern '.+'`错误外，对于有些股票会有如下错误

```
>>> df = ts.get_today_ticks('000725')
[Getting data:]######################'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
获取失败，请检查网络和URL
[Getting data:]######################'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
获取失败，请检查网络和URL
[Getting data:]######################'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
'float' object has no attribute 'replace'
获取失败，请检查网络和URL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/pyenv.tushare/lib/python2.7/site-packages/tushare/stock/trading.py", line 255, in get_today_ticks
    raise IOError(ct.NETWORK_URL_ERROR_MSG)
IOError: 获取失败，请检查网络和URL
```

versions:
tushare==0.7.4

**Comment by jimmysoa** [comment]
都是在mac系统下吗？

**Comment by mdsb100** [comment]
是的

**Comment by gzcf** [comment]
Mac +1

**Comment by jimmysoa** [comment]
我找个mac机器调试一下

**Comment by mikerommel** [comment]
请问目前这个问题解决了吗？最近几天一直显示IO错误：IOError(ct.NETWORK_URL_ERROR_MSG)       找到对应的url直接访问确实也有问题

**Comment by jimmysoa** [comment]
还没有找到mac电脑，好悲催啊

谁有mac系统帮忙调试一下啊啊啊啊啊啊啊

**Comment by mikerommel** [comment]
@jimmysoa   可以的呀，我帮你调试，具体怎么弄？我手上有macOS Sierra，有default 的 python 2.7  和 另外装的python 3.5（都装了tushare）。具体你有测试代码吗？   我发现每次到下午1：00开市后就报错，上午只是有时候报错（报错信息见附件）。不过具体根据get_today_ticks打印出来的url 确实也访问不了，怀疑不是代码的问题。

上面的screenshot就是我这台机子经常遇到的问题：（出现IOError exception就会提示html5lib 没有装，但应该是API接口去访问url的时候无法解析获得数据导致的，不太确定呀）

![screen shot 2017-05-04 at 21 38 10](https://cloud.githubusercontent.com/assets/24309149/25706383/df5873d2-3112-11e7-963f-f9f60534eba4.png)
