### ISSUE TITLE
获取某股票历史数据出错

### ISSUE THREAD

**Issue by fuermosi777** [waditu/tushare#34]
```
import tushare as ts
data = ts.get_h_data('000033',start='2014-06-29',end='2015-06-29')
```

给出以下错误信息：

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hao/venv/q-django/lib/python3.4/site-packages/tushare/stock/trading.py", line 392, in get_h_data
    if ((float(rt['high']) == 0) & (float(rt['low']) == 0)):
TypeError: 'NoneType' object is not subscriptable
```

可能是这股有点奇怪？既没有停牌，也没有数据

**Comment by cedricporter** [comment]
2014年4季度整个季度停牌了。

**Comment by fuermosi777** [comment]
@cedricporter 因为正常如果停牌的话 返回的dataFrame有一个empty的属性 而这个直接报错给出TypeError了

**Comment by cedricporter** [comment]
@fuermosi777 

另外，http://hq.sinajs.cn/rn=1828&list=sz000033 这个返回空。

```
var hq_str_sz000033="";
```

然后`get_realtime_quotes`就返回None了。

```
            rt = get_realtime_quotes(code)
            if ((float(rt['high']) == 0) & (float(rt['low']) == 0)):
                preClose = float(rt['pre_close'])
```

**Comment by jimmysoa** [comment]
@cedricporter 谢谢，我修复一下。
