### ISSUE TITLE
get_industry_classified()保存成csv报错

### ISSUE THREAD

**Issue by xlbaojun** [waditu/tushare#39]
把get_industry_classified()获得数据保存成csv的时候报错，保存成xls没问题  
把get_stock_basics()获得的数据保存成csv没问题

```python
data2 = ts.get_industry_classified()
print('\nget classified ...ok')
data2.to_csv('D:/Other/PY/data/industry_classified2.csv')
print('save classified ...ok')
```  
```
[Getting data:]#################################################Traceback (most recent call last):
  File "D:/Other/PY/tuShareGetStockList.py", line 13, in <module>
    data2.to_csv('D:/Other/PY/data/industry_classified2.csv')
  File "D:\Soft\Anaconda\lib\site-packages\pandas\core\frame.py", line 1189, in to_csv
    formatter.save()
  File "D:\Soft\Anaconda\lib\site-packages\pandas\core\format.py", line 1467, in save

get classified ...ok
    self._save()
  File "D:\Soft\Anaconda\lib\site-packages\pandas\core\format.py", line 1567, in _save
    self._save_chunk(start_i, end_i)
  File "D:\Soft\Anaconda\lib\site-packages\pandas\core\format.py", line 1594, in _save_chunk
    lib.write_csv_rows(self.data, ix, self.nlevels, self.cols, self.writer)
  File "pandas\lib.pyx", line 975, in pandas.lib.write_csv_rows (pandas\lib.c:17612)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

Process finished with exit code 1
```

**Comment by lubia** [comment]
像是编码问题，试试import部分改成这样
import sys
import tushare as ts
reload(sys)
sys.setdefaultencoding('utf8')

**Comment by xlbaojun** [comment]
感谢！确实是这个问题~
