### ISSUE TITLE
 pip文件有误，无法安装tushare。请注意下哦~~

### ISSUE THREAD

**Issue by morningtzh** [waditu/tushare#395]
`➜  ~ which pip 
pip: aliased to /Users/morningtzh/anaconda/bin/pip
➜  ~ which python
python: aliased to /Users/morningtzh/anaconda/bin/python3
➜  ~ pip install tushare

Collecting tushare
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/08/58/fe1c748b73565de9996871ae3fee47afbbe7686e83a7a89f27407a48033b/tushare-0.8.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/private/var/folders/cx/f429x4mn55q0j_p1p140xrhw0000gn/T/pip-build-rzhc4h25/tushare/tushare/futures/domestic.py", line 16, in <module>
        from urllib.request import urlencode
    ImportError: cannot import name 'urlencode'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cx/f429x4mn55q0j_p1p140xrhw0000gn/T/pip-build-rzhc4h25/tushare/setup.py", line 4, in <module>
        import tushare
      File "/private/var/folders/cx/f429x4mn55q0j_p1p140xrhw0000gn/T/pip-build-rzhc4h25/tushare/tushare/__init__.py", line 117, in <module>
        from tushare.futures.domestic import (get_cffex_daily, get_czce_daily,
      File "/private/var/folders/cx/f429x4mn55q0j_p1p140xrhw0000gn/T/pip-build-rzhc4h25/tushare/tushare/futures/domestic.py", line 19, in <module>
        from urllib2 import urlopen, Request
    ModuleNotFoundError: No module named 'urllib2'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/cx/f429x4mn55q0j_p1p140xrhw0000gn/T/pip-build-rzhc4h25/tushare/`

之前homebrew环境上python3安装过 tushre，今天刚装了 anaconda 发现 tushare 竟然装不上了。不知道为什么会 from urllib.request import urlencode 我看代码里确实是from urllib.parse import urlencode 而且历史记录也都是 parse 里面 import 的。

再看了下 pip 上的文件，里面是
`
    from urllib.request import urlencode
    `
导致了错误

希望 tushare 能将 pip 上的包修改下 谢谢~~~~~~~

**Comment by herozhang** [comment]
用普通python3环境，也是一样的问题

Downloading https://pypi.tuna.tsinghua.edu.cn/packages/08/58/fe1c748b73565de9996871ae3fee47afbbe7686e83a7a89f27407a48033b/tushare-0.8.0.zip (119kB)
    100% |████████████████████████████████| 122kB 2.0MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/private/var/folders/82/d4kmft096hl31367l9g0q2xr0000gn/T/pip-build-lxczojtz/tushare/tushare/futures/domestic.py", line 16, in <module>
        from urllib.request import urlencode
    ImportError: cannot import name 'urlencode'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/82/d4kmft096hl31367l9g0q2xr0000gn/T/pip-build-lxczojtz/tushare/setup.py", line 4, in <module>
        import tushare
      File "/private/var/folders/82/d4kmft096hl31367l9g0q2xr0000gn/T/pip-build-lxczojtz/tushare/tushare/__init__.py", line 117, in <module>
        from tushare.futures.domestic import (get_cffex_daily, get_czce_daily,
      File "/private/var/folders/82/d4kmft096hl31367l9g0q2xr0000gn/T/pip-build-lxczojtz/tushare/tushare/futures/domestic.py", line 19, in <module>
        from urllib2 import urlopen, Request
    ModuleNotFoundError: No module named 'urllib2'

**Comment by Rayda7** [comment]
tushare/tushare/futures/domestic.py中    from urllib.parse import urlencode

**Comment by leiliuliulei** [comment]
我在python 3.5上pip install tushare得到的错误和楼上一样：

    from urllib2 import urlopen, Request
ModuleNotFoundError: No module named 'urllib2'

**Comment by braindevices** [comment]
In py3, there is no urlib2 at all ...

> The urllib2 module has been split across several modules in Python 3 named urllib.request and urllib.error. The 2to3 tool will automatically adapt imports when converting your sources to Python 3.

**Comment by RobotJiang** [comment]
如果是 conda 安装的 python , 请先切换到对应环境，然后在那个环境重新安装 pip . 最后通过 pip 来安装 tushare 。

**Comment by yanghui1228** [comment]
在mac上试过已经可以安装新版了

yang.hui@icloud.com

On 12 Jun 2017, at 1:44 PM, RobotJiang <notifications@github.com> wrote:

如果是 conda 安装的 python , 请先切换到对应环境，然后在那个环境重新安装 pip . 最后通过 pip 来安装 tushare 。
