### ISSUE TITLE
ts.get_stock_basics() does not work recently

### ISSUE THREAD

**Issue by walterzy** [waditu/tushare#421]
print(ts.__version__)
0.6.8

ts.get_stock_basics()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tushare/stock/fundamental.py", line 54, in get_stock_basics
    text = urlopen(request, timeout=1000).read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>

**Comment by jimmysoa** [comment]
升级到最新版就可以了
