### ISSUE TITLE
Install tushare error

### ISSUE THREAD

**Issue by xuesj** [waditu/tushare#431]
pip2.7 install tushare==0.8.4
Collecting tushare==0.8.4
  Using cached tushare-0.8.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6g/qpx730ks6g34j_6zrp0y7jk80000gn/T/pip-build-B9Mu3L/tushare/setup.py", line 4, in <module>
        import tushare
      File "tushare/__init__.py", line 117, in <module>
        from tushare.futures.domestic import (get_cffex_daily, get_czce_daily,
      File "tushare/futures/domestic.py", line 11, in <module>
        from bs4 import BeautifulSoup
      File "/anaconda2.7/lib/python2.7/site-packages/bs4/__init__.py", line 30, in <module>
        from .builder import builder_registry, ParserRejectedMarkup
      File "/anaconda2.7/lib/python2.7/site-packages/bs4/builder/__init__.py", line 314, in <module>
        from . import _html5lib
      File "/anaconda2.7/lib/python2.7/site-packages/bs4/builder/_html5lib.py", line 70, in <module>
        class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
    AttributeError: 'module' object has no attribute '_base'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/6g/qpx730ks6g34j_6zrp0y7jk80000gn/T/pip-build-B9Mu3L/tushare/

**Comment by xuesj** [comment]
just find a solution from http://blog.csdn.net/justdoitjs/article/details/63689061
pip install --upgrade html5lib==1.0b8
