### ISSUE TITLE
获取中小板和创业板分类错误

### ISSUE THREAD

**Issue by firefenta** [waditu/tushare#46]
创业板和中小板都是相似的问题，沪深300和中证500没有问题。

``` python
import pandas as pd
import tushare as ts
pd.set_option('display.width', 200)
zxb = ts.get_sme_classified()
```

```
"C:\Program Files\Anaconda3\python.exe" "D:/MyDoc/Cloud Station/Investment/Python/PQuant/A Share DK Pailie.py"
Traceback (most recent call last):
  File "D:/MyDoc/Cloud Station/Investment/Python/PQuant/A Share DK Pailie.py", line 8, in <module>
    zxb = ts.get_sme_classified()
  File "C:\Program Files\Anaconda3\lib\site-packages\tushare\stock\classifying.py", line 113, in get_sme_classified
    df = fd.get_stock_basics()
  File "C:\Program Files\Anaconda3\lib\site-packages\tushare\stock\fundamental.py", line 44, in get_stock_basics
    text = urlopen(request, timeout=10).read()
  File "C:\Program Files\Anaconda3\lib\urllib\request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Anaconda3\lib\urllib\request.py", line 469, in open
    response = meth(req, response)
  File "C:\Program Files\Anaconda3\lib\urllib\request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files\Anaconda3\lib\urllib\request.py", line 507, in error
    return self._call_chain(*args)
  File "C:\Program Files\Anaconda3\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "C:\Program Files\Anaconda3\lib\urllib\request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

Process finished with exit code 1

```

**Comment by firefenta** [comment]
已经好了，可以读取，前两天不知道是为什么会有HTTP Error 403: Forbidden的错误。
