### ISSUE TITLE
600018数据获取错误

### ISSUE THREAD

**Issue by firefenta** [waditu/tushare#47]
日线数据没有问题，周线月线出现错误。

``` python
import pandas as pd
import tushare as ts

RawData = ts.get_hist_data('600018', start='2015-01-01', end='2015-07-27', ktype='W')
print(RawData)
```

```
Traceback (most recent call last):
  File "D:/MyDoc/LCW/Investment/Python/PQuant/test1.py", line 9, in <module>
    RawData = ts.get_hist_data('600018', start='2015-01-01', end='2015-07-27', ktype='W')
  File "C:\Program Files\Anaconda3\lib\site-packages\tushare\stock\trading.py", line 84, in get_hist_data
    df[col] = df[col].astype(float)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\generic.py", line 2411, in astype
    dtype=dtype, copy=copy, raise_on_error=raise_on_error, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\internals.py", line 2504, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\internals.py", line 2459, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\internals.py", line 373, in astype
    values=values, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\internals.py", line 403, in _astype
    values = com._astype_nansafe(self.values.ravel(), dtype, copy=True)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\core\common.py", line 2734, in _astype_nansafe
    return arr.astype(dtype)
ValueError: could not convert string to float: 

Process finished with exit code 1
```

**Comment by cedricporter** [comment]
http://api.finance.ifeng.com/akweekly/?code=sh600018&type=last

这个返回的前面的很多row的 turnover 都是空字符串，所以

```
            for col in cols[1:]:
                df[col] = df[col].astype(float)
```

这里将空字符串转成float会报错。

作者这里是觉得将其变成nan好还是变成0好？
