### ISSUE TITLE
怎样获取50ETF期权的信息？

### ISSUE THREAD

**Issue by fffweb** [waditu/tushare#474]
请教下，这个软件能获取50ETF期权的信息吗？
按说明操作，有下面问题
＃获取期权合约编码，交易代码，交易市场，标的等相关信息
**>>> fd = ts.Options()**
璇疯缃€氳仈鏁版嵁鎺ュ彛鐨則oken鍑瘉鐮

**>>> df = fd.Opt(contractStatus='L,DE', field='optID,secShortName,varShortName,listDate')**
Traceback (most recent call last):
File "", line 1, in 
File "D:\Python27\lib\site-packages\tushare\datayes\options.py", line 30, in Opt
varSecID, varticker, field))
File "D:\Python27\lib\site-packages\tushare\util\common.py", line 84, in getData
raise e
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by jimmysoa** [comment]
新版发布的时候会支持

**Comment by fffweb** [comment]
谢谢，能否告知新版大概什么时候会发布，如果知道具体时间，对于我们下一步采用什么战略比较重要。

**Comment by jimmysoa** [comment]
等新版

**Comment by fffweb** [comment]
新版本可以了
