### ISSUE TITLE
get_industry_classified返回的结果数据不全

### ISSUE THREAD

**Issue by zj519718645** [waditu/tushare#496]
调用get_industry_classified返回的数据不全，目前有3300多只股票，而这个get_industry_classified却只能拿到2392条数据。将近1000只股票的行业数据拿不到。

**Comment by jimmysoa** [comment]
大概知道什么原因了，新版更正，谢谢。

**Comment by xiaokesong** [comment]
好几个接口都报了gbk相关的错误，请问是我python版本的问题吗，目前Python 3.6.4
[Getting data:]#Traceback (most recent call last):
  File "test.py", line 12, in <module>
    stock = ts.get_concept_classified()
  File "C:\Users\kesong\AppData\Local\Programs\Python\Python36\lib\site-packages\tushare\stock\classifying.py", line 73, in get_concept_classified
    rowDf =  _get_detail(row[0])
  File "C:\Users\kesong\AppData\Local\Programs\Python\Python36\lib\site-packages\tushare\stock\classifying.py", line 188, in _get_detail
    text = text.decode('gbk')
UnicodeDecodeError: 'gbk' codec can't decode byte 0xab in position 1882: illegal multibyte sequence
