### ISSUE TITLE
get_day_all 函数在 2017-06-23 这天遇到 HTTP ERROR 404

### ISSUE THREAD

**Issue by zhuzhi** [waditu/tushare#515]
运行结果如下, 2017-06-23 这天为交易日, 但是数据获取遇到 404. 前一个交易日 2017-06-22 和后一个交易日 2017-06-26 都可正常获取.
```python
>>> tushare.get_day_all('2017-06-23')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tushare/stock/trading.py", line 791, in get_day_all
    dtype={'code':'object'})
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 392, in _read
    filepath_or_buffer, encoding, compression)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/common.py", line 186, in get_filepath_or_buffer
    req = _urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by jiazheng2222** [comment]
貌似大佬的文件服务器挂了，等他修复吧

**Comment by jimmysoa** [comment]
这个接口的历史数据还不多
