### ISSUE TITLE
查询时间跨度大时候， 会出现网络错误

### ISSUE THREAD

**Issue by zengyee** [waditu/tushare#523]
>>> ts.get_h_data('600701',start='1995-06-01')
[Getting data:]#####################################HTTP Error 456: 
HTTP Error 456: 
HTTP Error 456: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jeff/.local/lib/python3.6/site-packages/tushare/stock/trading.py", line 437, in get_h_data
    retry_count, pause)
  File "/home/jeff/.local/lib/python3.6/site-packages/tushare/stock/trading.py", line 569, in _parse_fq_data
    raise IOError(ct.NETWORK_URL_ERROR_MSG)
OSError: 获取失败，请检查网络.
>>>

**Comment by jimmysoa** [comment]
建议用ts.bar接口
