### ISSUE TITLE
IOError: 获取失败，请检查网络

### ISSUE THREAD

**Issue by williamjie** [waditu/tushare#531]
object of type 'NoneType' has no len()
object of type 'NoneType' has no len()
object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "get_code_data.py", line 138, in <module>
    DateClass().GetDate(stock_code,file_name_qfq,file_name,file_name_hfq,qfq_update_flag,flag_update,hfq_update_flag)
  File "get_code_data.py", line 38, in GetDate
    df_cons = ts.bar(stock_code,conn=cons,adj='qfq',ma=[60,120,250])
  File "/Users/zj/anaconda2/lib/python2.7/site-packages/tushare/stock/trading.py", line 928, in bar
    raise IOError(ct.NETWORK_URL_ERROR_MSG)

出现这种情况，一般来说是出现异常情况；是否		cons = ts.get_apis()
conn长连接断开了

**Comment by jimmysoa** [comment]
bar接口加一个try功能

**Comment by mjzxcvbnm** [comment]
runfile('D:/Python/Python/stock/stockTest.py', wdir='D:/Python/Python/stock')
'datetime'
'datetime'
'datetime'
Traceback (most recent call last):

  File "<ipython-input-4-e8873426b5d7>", line 1, in <module>
    runfile('D:/Python/Python/stock/stockTest.py', wdir='D:/Python/Python/stock')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Python/Python/stock/stockTest.py", line 488, in <module>
    df = ts.bar('600005', conn=cons, freq='D', start_date='2016-01-01', end_date='')

  File "C:\ProgramData\Anaconda3\lib\site-packages\tushare\stock\trading.py", line 923, in bar
    raise IOError(ct.NETWORK_URL_ERROR_MSG)

OSError: 获取失败，请检查网络.


比如输入股票代码600005，就会出现网络错误，这个是不是返回None比较合理？

**Comment by ariescc** [comment]
请问网络错误这个问题是怎么回事？是因为这个股票行情获取不到吗（网络实际是连接着的）

**Comment by jimmysoa** [comment]
访问太频繁？另外是否conn重复申请了？

**Comment by williamjie** [comment]
谢谢，问题解决：conn 重复申请了的原因；
