### ISSUE TITLE
tushare.bar()函数获取郑商所行情报错IOError 

### ISSUE THREAD

**Issue by feizei2008** [waditu/tushare#536]
米哥，我发现Ver1.0.5版本的bar函数取郑商所品种行情的时候会报错，其他没有问题

import tushare as ts
cons = ts.get_apis()
ts.bar('FG805', conn=cons, freq='D', asset='X', start_date='2017-11-01', end_date='')

报错如下：
index 0 is out of bounds for axis 0 with size 0
index 0 is out of bounds for axis 0 with size 0
index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):

  File "<ipython-input-26-e228fa46eca0>", line 1, in <module>
    runfile('D:/pythonLearn/python脚本/tushare-bar-tick行情.py', wdir='D:/pythonLearn/python脚本')

  File "d:\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "d:\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "D:/pythonLearn/python脚本/tushare-bar-tick行情.py", line 26, in <module>

  File "d:\Anaconda2\lib\site-packages\tushare\stock\trading.py", line 928, in bar
    raise IOError(ct.NETWORK_URL_ERROR_MSG)

IOError: 鑾峰彇澶辫触锛岃�妫�煡缃戠粶.

**Comment by feizei2008** [comment]
解决了，把SM805改成sm1805即可。

**Comment by jimmysoa** [comment]
ok
