### ISSUE TITLE
get_industry_classified()和get_concept_classified()提取数据报错。

### ISSUE THREAD

**Issue by Gabrielvon** [waditu/tushare#555]
以下两个公式报错：KeyError: "['date'] not in index" 和 TypeError: showtraceback() got an unexpected keyword argument 'running_compiled_code'
tushare.get_industry_classified()
tushare.get_concept_classified()

```
Python 3.6.2 |Anaconda custom (x86_64)| (default, Sep 21 2017, 18:29:43) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 6.2.1
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['/Users/gabrielfeng/Nutstore/MyNutshell/FanCapitial'])
sys.path.append('/Users/gabrielfeng/Nutstore/MyNutshell/FanCapitial/RefPkg')
Python 3.6.2 |Anaconda custom (x86_64)| (default, Sep 21 2017, 18:29:43) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
import tushare as ts
Backend MacOSX is interactive backend. Turning interactive mode on.
```
```
**indus_cls = ts.get_industry_classified()**
[Getting data:]#Traceback (most recent call last):
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-270b7eb69010>", line 1, in <module>
    indus_cls = ts.get_industry_classified()
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/tushare/stock/classifying.py", line 51, in get_industry_classified
    rowDf =  _get_detail(row[0], retry_count=10, pause=0.01)
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/tushare/stock/classifying.py", line 200, in _get_detail
    df = df[ct.FOR_CLASSIFY_B_COLS]
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2133, in __getitem__
    return self._getitem_array(key)
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2177, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1269, in _convert_to_indexer
    .format(mask=objarr[mask]))
KeyError: "['date'] not in index"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2927, in run_code
    self.showtraceback(running_compiled_code=True)
TypeError: showtraceback() got an unexpected keyword argument 'running_compiled_code'
```
```
conce_cls = ts.get_concept_classified()
[Getting data:]#Traceback (most recent call last):
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-79f00c282839>", line 1, in <module>
    conce_cls = ts.get_concept_classified()
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/tushare/stock/classifying.py", line 73, in get_concept_classified
    rowDf =  _get_detail(row[0])
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/tushare/stock/classifying.py", line 200, in _get_detail
    df = df[ct.FOR_CLASSIFY_B_COLS]
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2133, in __getitem__
    return self._getitem_array(key)
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2177, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1269, in _convert_to_indexer
    .format(mask=objarr[mask]))
KeyError: "['date'] not in index"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2927, in run_code
    self.showtraceback(running_compiled_code=True)
TypeError: showtraceback() got an unexpected keyword argument 'running_compiled_code'

```

**Comment by philios** [comment]
碰到了同样问题，1.0.7版。把 tushare 安装目录下 stock/cons.py 里 FOR_CLASSIFY_B_COLS = ['date', 'code','name'] 的 'date', 删掉就好了，改成 FOR_CLASSIFY_B_COLS = ['code','name'] ，不知道是新版引入的问题，还是新浪的API改了

**Comment by Gabrielvon** [comment]
@philios 可以，非常感谢。
