### ISSUE TITLE
接口报gbk错误

### ISSUE THREAD

**Issue by xiaokesong** [waditu/tushare#568]
好几个接口都报了gbk相关的错误，请问是我python版本的问题吗，目前Python 3.6.4
[Getting data:]#Traceback (most recent call last):
File "test.py", line 12, in 
stock = ts.get_concept_classified()
File "C:\Users\kesong\AppData\Local\Programs\Python\Python36\lib\site-packages\tushare\stock\classifying.py", line 73, in get_concept_classified
rowDf = _get_detail(row[0])
File "C:\Users\kesong\AppData\Local\Programs\Python\Python36\lib\site-packages\tushare\stock\classifying.py", line 188, in _get_detail
text = text.decode('gbk')
UnicodeDecodeError: 'gbk' codec can't decode byte 0xab in position 1882: illegal multibyte sequence

**Comment by jimmysoa** [comment]
3.6的还没测过，尴尬了

**Comment by xiaokesong** [comment]
您好，请教下现在用哪个版本比较合适

**Comment by jimmysoa** [comment]
to_sql要看是什么错,一般2.7和3.5都挺稳定的
