### ISSUE TITLE
获取行业指数的时候不能获取全指公用、全指工业、全指电信的数据

### ISSUE THREAD

**Issue by yammi1230** [waditu/tushare#665]
获取行业指数的时候不能获取全指公用(000995)、全指工业(000988)、全指电信(000994)的数据
源代码如下：
`A='000988'`
`df=ts.bar(A,conn=cons,asset='INDEX')`
`df['close']=df['close'].astype('float64')`
> 

错误信息：
'datetime'
'datetime'
'datetime'
Traceback (most recent call last):

  File "<ipython-input-6-b0ee14ee0b6a>", line 2, in <module>
    df =ts.bar(A,conn=cons,asset='INDEX')

  File "C:\Users\Yammi1230\Anaconda3\lib\site-packages\tushare\stock\trading.py", line 926, in bar
    raise IOError(ct.NETWORK_URL_ERROR_MSG)

OSError: 获取失败，请检查网络.

**Comment by jimmysoa** [comment]
这是中证指数，这样写： df = ts.bar('000988', conn=cons, asset='X', market=62)
