### ISSUE TITLE
最新版本安装错误

### ISSUE THREAD

**Issue by cilia** [waditu/tushare#68]
`pip install tushare`

错误记录：

```
Collecting tushare
  Downloading tushare-0.4.0.zip (85kB)
    100% |████████████████████████████████| 86kB 3.0MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/pz/pv_tvqkd7jj9l2b4pk8j8hdm0000gp/T/pip-build-3kyqbyc4/tushare/setup.py", line 4, in <module>
        import tushare
      File "/private/var/folders/pz/pv_tvqkd7jj9l2b4pk8j8hdm0000gp/T/pip-build-3kyqbyc4/tushare/tushare/__init__.py", line 7, in <module>
        from tushare.stock.trading import (get_hist_data, get_tick_data,
      File "/private/var/folders/pz/pv_tvqkd7jj9l2b4pk8j8hdm0000gp/T/pip-build-3kyqbyc4/tushare/tushare/stock/trading.py", line 13, in <module>
        import lxml.html
    ImportError: No module named 'lxml'
```

**Comment by liaosiwei** [comment]
this is caused by lacking the dependency of python package 'lxml'. You can install it by "pip install lxml"

**Comment by zezhou** [comment]
是不是可以在 requirements.txt 中加入 lxml

**Comment by zezhou** [comment]
我看有人已经提pr了，只需要合并了
https://github.com/waditu/tushare/pull/44

**Comment by cilia** [comment]
@zezhou @jimmysoa still not working, the latest 0.4.3 release continues to split out error for missing `lxml` package.

**Comment by kawing-chiu** [comment]
竟然这么久了还没有在setup.py加上dependencies，好山寨啊。
