### ISSUE TITLE
sh_margins和sh_margin_details两个沪市融资融券的函数失效了

### ISSUE THREAD

**Issue by lidanger** [waditu/tushare#708]
ts.sh_margin_details('2018-07-09', '600848')
显示
[Getting data:]#HTTP Error 403: Forbidden
#HTTP Error 403: Forbidden
#HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "<pyshell#23>", line 1, in <module>
    ts.sh_margin_details('2018-07-09', '600848')
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tushare\stock\reference.py", line 662, in sh_margin_details
    pause=pause)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tushare\stock\reference.py", line 710, in _sh_mx
    raise IOError(ct.NETWORK_URL_ERROR_MSG)
OSError: 获取失败，请检查网络.

**Comment by lidanger** [comment]
还有shibor相关函数，没有任何返回，也不报错
tushare 版本 1.2.4

**Comment by lidanger** [comment]
我看了 tushare.stock.trading.get_security()这个函数，似乎也没有上证相关的信息
@zhsso @jimmysoa

**Comment by jimmysoa** [comment]
请切换到pro版，https://tushare.pro/document/2?doc_id=58
