### ISSUE TITLE
这是啥错误。。。开头好好的

### ISSUE THREAD

**Issue by mttbx** [waditu/tushare#754]
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    test1(pro)
  File "test.py", line 13, in test1
    data = pro.stock_basic(exchange_id='', is_hs='')
  File "/usr/local/lib/python3.6/dist-packages/tushare/pro/client.py", line 90, in query
    data = self.req_http_api(req_params)
  File "/usr/local/lib/python3.6/dist-packages/tushare/pro/client.py", line 75, in req_http_api
    raise Exception(result['msg'])
Exception: 系统内部错误

**Comment by jimmysoa** [comment]
现在好了的
