### ISSUE TITLE
官网-区块链bug

### ISSUE THREAD

**Issue by simon-zzm** [waditu/tushare#911]
https://tushare.pro/document/41?doc_id=75
错误
Traceback (most recent call last):
  File "/platform/software/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/platform/release/tushare_pro/tushare_pro/frontend/handlers/document.py", line 30, in get
    % (doc.id, self.get_remote_ip(), self.get_current_uid()))
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by jimmysoa** [comment]
没有这个文档了，请从官网里点击阅读
