### ISSUE TITLE
AttributeError: 'module' object has no attribute 'stock'

### ISSUE THREAD

**Issue by whughchen** [waditu/tushare#92]
C:\Users\ghchen>python
Python 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
》 import tushare as ts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\tushare__init__.py", line 34, in <module>
    from tushare.stock.classifying import (get_industry_classified, get_concept_classified,
  File "C:\Python27\lib\site-packages\tushare\stock\classifying.py", line 18, in <module>
    import tushare.stock.fundamental as fd
AttributeError: 'module' object has no attribute 'stock'

**Comment by callmewhy** [comment]
+1

**Comment by jimmysoa** [comment]
安装没成功，或者是环境变量有问题。

**Comment by callmewhy** [comment]
我在 Notebook 里也遇到这个问题，重启一下 Kernel 就行了
