### ISSUE TITLE
获取沪深上市公司基本情况接口get_stock_basics('2017-06-23')，urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by matrixleon18** [waditu/tushare#947]
>>>import tushare as ts
>>>ts.get_stock_basics('2017-06-23')

系统返回错误：
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Python37\lib\site-packages\tushare\stock\fundamental.py", line 54, in get_stock_basics
    text = urlopen(request, timeout=10).read()
  File "D:\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "D:\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "D:\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\Python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by matrixleon18** [comment]
tushare上注册的ID号: 13052196219

**Comment by LG-Symphony** [comment]
是不是没有写token

**Comment by matrixleon18** [comment]
这句不是pro的接口，不用写token。
而且把时间稍微提前一天，就正常了。例如：
>>>import tushare as ts
>>>ts.get_stock_basics('2017-06-22')

如果往后移一天，就出现了和“2017-06-23”一样的问题。例如：
>>>import tushare as ts
>>>ts.get_stock_basics('2017-06-24')

再看看，2017-06-24是周六，证券市场休市，没有返回是正常的。
估计是tushare把 “2017-06-23”这一天当作休市。实际上A股是有交易的。

同样的问题也出现在了“2016-08-19”这一天。

**Comment by jimmysoa** [comment]
这个接口缺失的数据暂时无法修复，建议用pro版接口
