### ISSUE TITLE
python3 使用profit_data报错

### ISSUE THREAD

**Issue by fayeshine** [waditu/tushare#95]
[Getting data:]cannot use a string pattern on a bytes-like object
cannot use a string pattern on a bytes-like object
cannot use a string pattern on a bytes-like object
Traceback (most recent call last):

  File "<ipython-input-9-0f81b386ad34>", line 1, in <module>
    get_profit_data()

  File "<ipython-input-4-07eadf145f52>", line 38, in get_profit_data
    df = profit_data(year=i, top=1000000)

  File "/home/wenjian/pkgs/tushare/tushare/stock/reference.py", line 66, in profit_data
    df, pages = _dist_cotent(year, 0, retry_count, pause)

  File "/home/wenjian/pkgs/tushare/tushare/stock/reference.py", line 153, in _dist_cotent
    raise IOError(ct.NETWORK_URL_ERROR_MSG)

OSError: 获取失败，请检查网络和URL

**Comment by jimmysoa** [comment]
@fayeshine python3测试通过没问题，你的参数year能否调试一下看是什么值？

**Comment by fayeshine** [comment]
def get_profit_data():
    year = strftime('%Y', localtime(time.time()))
    res = DataFrame()
    for i in range(1990,int(year)+1):
        df = profit_data(year=i, top=1000000)
        if df.ix[0].code != '000nan':
            res = concat([res,df], axis=0)
    return res

这是我的代码
