### ISSUE TITLE
IOError:获取失败，请检查网络和URL

### ISSUE THREAD

**Issue by LMJWEIJY** [waditu/tushare#96]
/Users/wjy/anaconda/bin/python /Users/wjy/PycharmProjects/MyTushare/hist.py
[Errno 54] Connection reset by peer
[Errno 54] Connection reset by peer
[Errno 54] Connection reset by peer
Traceback (most recent call last):
  File "/Users/wjy/PycharmProjects/MyTushare/hist.py", line 3, in <module>
    ts.get_hist_data('600848')
  File "/Users/wjy/anaconda/lib/python2.7/site-packages/tushare/stock/trading.py", line 95, in get_hist_data
    raise IOError(ct.NETWORK_URL_ERROR_MSG)
IOError: 获取失败，请检查网络和URL

Process finished with exit code 1

**Comment by jimmysoa** [comment]
今天凤凰财经的行情挂了，影响了get_hist_data，在下周开盘前应该能恢复。可以先用get_h_data替代来获取历史数据
@LMJWEIJY
