### ISSUE TITLE
tushare1.2.23升级后无法进入

### ISSUE THREAD

**Issue by yyxochen** [waditu/tushare#989]
刚才升级一下：
```
pip install tushare --upgrade

Installing collected packages: tushare
  Found existing installation: tushare 1.2.20
    Uninstalling tushare-1.2.20:
      Successfully uninstalled tushare-1.2.20
  Running setup.py install for tushare ... done
Successfully installed tushare-1.2.23
```
之后使用就报错：
```
 import tushare as ts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\tushare\__init__.py", line 82, in <module>
    from tushare.pro.data_pro import (pro_api, pro_bar)
ImportError: cannot import name 'pro_api' from 'tushare.pro.data_pro' (C:\Python37\lib\site-packages\tushare\pro\data_pro.py)
```

**Comment by jimmysoa** [comment]
请升级到1.2.25版本，谢谢
