### ISSUE TITLE
网站邮箱注册报错

### ISSUE THREAD

**Issue by Aoseala** [waditu/tushare#993]
错误信息如下：

Traceback (most recent call last):
  File "/platform/release/tushare_pro/tushare_pro/util/mail.py", line 53, in send
    client.connect(self.host, 25)
  File "/platform/software/anaconda3/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/platform/software/anaconda3/lib/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/platform/software/anaconda3/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/platform/software/anaconda3/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/platform/software/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/platform/release/tushare_pro/tushare_pro/frontend/handlers/site.py", line 113, in get
    UserService.send_register_mail(account)
  File "/platform/release/tushare_pro/tushare_pro/frontend/service/user.py", line 78, in send_register_mail
    mail.send(template['title'], template['content'].format(code=verify_code))
  File "/platform/release/tushare_pro/tushare_pro/util/mail.py", line 69, in send
    raise Exception('邮件发送异常')
Exception: 邮件发送异常

tushare ID：Aoseala    邮箱： aoseala@163.com

**Comment by jimmysoa** [comment]
收到,积分已添加
