### ISSUE TITLE
网站手机号注册也报错

### ISSUE THREAD

**Issue by Aoseala** [waditu/tushare#994]
Traceback (most recent call last):
  File "/platform/software/anaconda3/lib/python3.6/site-packages/aliyunsdkcore/client.py", line 231, in implementation_of_do_action
    status, headers, body = http_response.get_response_object()
  File "/platform/software/anaconda3/lib/python3.6/site-packages/aliyunsdkcore/http/http_response.py", line 71, in get_response_object
    return self.get_http_response_object()
  File "/platform/software/anaconda3/lib/python3.6/site-packages/aliyunsdkcore/http/http_response.py", line 96, in get_http_response_object
    self.__connection.connect()
  File "/platform/software/anaconda3/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/platform/software/anaconda3/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/platform/software/anaconda3/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/platform/software/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/platform/release/tushare_pro/tushare_pro/frontend/handlers/site.py", line 111, in get
    UserService.send_register_sms(account)
  File "/platform/release/tushare_pro/tushare_pro/frontend/service/user.py", line 94, in send_register_sms
    send_ok = Sms.send(unique_id, phone, REGISTER_TEMPLATE_ID, params)
  File "/platform/release/tushare_pro/tushare_pro/util/sms.py", line 68, in send
    response = cls.client().do_action_with_exception(request)
  File "/platform/software/anaconda3/lib/python3.6/site-packages/aliyunsdkcore/client.py", line 259, in do_action_with_exception
    status, headers, body = self.implementation_of_do_action(acs_request)
  File "/platform/software/anaconda3/lib/python3.6/site-packages/aliyunsdkcore/client.py", line 236, in implementation_of_do_action
    error_msg.get_msg('SDK_SERVER_UNREACHABLE') + ': ' + str(e))
aliyunsdkcore.acs_exception.exceptions.ClientException: SDK.ServerUnreachable Unable to connect server: [Errno -3] Temporary failure in name resolution

tushare ID：Aoseala   邮箱：aoseala@163.com

**Comment by jimmysoa** [comment]
我们尽快处理,另外是什么类型的手机号?

**Comment by Aoseala** [comment]
> 我们尽快处理,另外是什么类型的手机号?
170的手机号
